language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep_history: true
  on:
    branch: master